# textVersion: 2026-06-02 v1.01
# Changes: Added root redirect route to prevent 404 on /migration prefix from hamburger menu; fixed fallback dir-name parsing to only apply when test_summary.json missing/failed; dynamic mimetype for HTML/MD reports; removed unused imports; added jsonify for API.

#!/usr/bin/env python3
#
# migration_routes.py - Routes for Live Migration Results page
# Displays HTML reports generated by exa_vm_migration_monitor.py --report
#
# This blueprint provides:
#   GET /migration/           -> redirects to /migration/results
#   GET /migration/results    -> table of all migration test runs
#   GET /migration/view/...   -> serves generated analysis_report.html or .md
#   GET /migration/api/runs   -> JSON list (for future AJAX/dashboard use)

from flask import (
    Blueprint, render_template, current_app, send_from_directory,
    redirect, url_for, jsonify
)
from flask_login import login_required
import os
import json
from datetime import datetime

migration_bp = Blueprint('migration', __name__, url_prefix='/migration', template_folder='templates')


@migration_bp.route('/')
@login_required
def migration_root():
    """Redirect bare /migration prefix to the results landing page.
    
    This prevents 404 errors if the hamburger menu links to the
    blueprint mount point instead of the explicit /results sub-route.
    """
    return redirect(url_for('migration.live_migration_results'))


def get_migration_test_runs():
    """Scan the migration test output directory and return list of test runs with metadata."""
    reports_dir = current_app.config.get(
        'MIGRATION_REPORTS_DIR',
        os.path.expanduser('~/mchafin/lm_test/migration_tests')  # Default; override in app config if needed
    )
    runs = []
    if not os.path.isdir(reports_dir):
        return runs

    for entry in sorted(os.listdir(reports_dir), reverse=True):
        if '_test_' not in entry:
            continue
        full_path = os.path.join(reports_dir, entry)
        if not os.path.isdir(full_path):
            continue

        info = {
            'dir_name': entry,
            'full_path': full_path,
            'vm': 'Unknown',
            'source_host': 'N/A',
            'dest_host': 'N/A',
            'mode': 'live',
            'test_date': 'N/A',
            'has_report': False,
            'report_url': None
        }

        summary_loaded = False
        summary_file = os.path.join(full_path, 'test_summary.json')
        if os.path.exists(summary_file):
            try:
                with open(summary_file, 'r') as f:
                    summary = json.load(f)
                info['vm'] = summary.get('domain', entry.split('_')[0])
                info['mode'] = summary.get('mode', 'live')
                summary_loaded = True
            except Exception:
                pass

        # Fallback: parse directory name ONLY if we didn't get good data from summary
        # e.g. vm_live_test_20260528123456...
        if not summary_loaded:
            parts = entry.split('_')
            if len(parts) >= 1:
                info['vm'] = parts[0]
            if len(parts) >= 2:
                info['mode'] = parts[1]

        # Extract timestamp for date (prefer this over fallback date)
        try:
            parts = entry.split('_')
            ts_part = [p for p in parts if p.isdigit() and len(p) >= 14][0]
            dt = datetime.strptime(ts_part[:14], '%Y%m%d%H%M%S')
            info['test_date'] = dt.strftime('%Y-%m-%d %H:%M:%S')
        except Exception:
            info['test_date'] = entry.split('_')[-1] if 'parts' in locals() else 'N/A'

        # Check for the HTML report generated by --report flag
        report_html = os.path.join(full_path, 'analysis_report.html')
        if os.path.exists(report_html):
            info['has_report'] = True
            info['report_url'] = f'/migration/view/{entry}/analysis_report.html'

        # Also check for MIGRATION_TEST_SUMMARY.md as fallback
        if not info['has_report']:
            md_file = os.path.join(full_path, 'MIGRATION_TEST_SUMMARY.md')
            if os.path.exists(md_file):
                info['has_report'] = True
                info['report_url'] = f'/migration/view/{entry}/MIGRATION_TEST_SUMMARY.md'

        runs.append(info)

    return runs


@migration_bp.route('/results')
@login_required
def live_migration_results():
    """Landing page with table of all migration test runs."""
    runs = get_migration_test_runs()

    # Sort by test_date descending (newest first)
    def parse_date(r):
        try:
            return datetime.strptime(r.get('test_date', ''), '%Y-%m-%d %H:%M:%S')
        except Exception:
            return datetime.min

    runs = sorted(runs, key=parse_date, reverse=True)

    return render_template(
        'migration/live_migration_results.html',
        runs=runs,
        reports_dir=current_app.config.get('MIGRATION_REPORTS_DIR', '~/migration_tests')
    )


@migration_bp.route('/view/<path:report_path>')
@login_required
def view_report(report_path):
    """Serve a specific generated report HTML (or MD) safely."""
    reports_dir = current_app.config.get(
        'MIGRATION_REPORTS_DIR',
        os.path.expanduser('~/mchafin/lm_test/migration_tests')
    )
    # Security: only serve files under the reports dir (path traversal protection)
    safe_path = os.path.normpath(os.path.join(reports_dir, report_path))
    if not safe_path.startswith(os.path.abspath(reports_dir)):
        return "Invalid path", 403

    directory = os.path.dirname(safe_path)
    filename = os.path.basename(safe_path)

    # Choose appropriate mimetype so browsers render .html and .md correctly
    if filename.lower().endswith(('.html', '.htm')):
        mimetype = 'text/html'
    elif filename.lower().endswith('.md'):
        mimetype = 'text/markdown'
    else:
        mimetype = 'text/plain'

    return send_from_directory(directory, filename, mimetype=mimetype)


@migration_bp.route('/api/runs')
@login_required
def api_migration_runs():
    """JSON API for future frontend enhancements (AJAX tables, etc.)."""
    return jsonify({'runs': get_migration_test_runs()})
